let selectedStory=0,selectedShort=0;const $=s=>document.querySelector(s);const pages=['dashboard','fondos','historias','crear','editor','historial','config'];
function show(id){pages.forEach(x=>$('#'+x).classList.toggle('active',x===id));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));$('#title').textContent=document.querySelector(`button[data-page="${id}"]`).textContent; if(id==='fondos')loadVideos();if(id==='historias'||id==='crear')loadStories();if(id==='historial')loadShorts()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.page));
async function upload(){let f=$('#file').files[0];if(!f)return msg('#uploadMsg','Elegí un archivo.','err');let fd=new FormData();fd.append('file',f);msg('#uploadMsg','Subiendo y analizando frames… puede tardar según el video.','loading');try{let r=await fetch('/api/videos/upload',{method:'POST',body:fd}),j=await r.json();if(!r.ok)throw Error(j.detail);msg('#uploadMsg',`Listo: ${j.clips} clips detectados y puntuados.`,'ok');loadVideos()}catch(e){msg('#uploadMsg',e.message,'err')}}
async function importUrl(){let fd=new FormData();fd.append('url',$('#url').value);fd.append('rights',$('#rights').checked);try{let r=await fetch('/api/import-url',{method:'POST',body:fd}),j=await r.json();if(!r.ok)throw Error(j.detail);msg('#urlMsg','Importado.','ok')}catch(e){msg('#urlMsg',e.message,'err')}}
async function loadVideos(){let a=await fetch('/api/videos').then(r=>r.json());$('#videos').innerHTML=a.length?`<table class=table><tr><th>Nombre</th><th>Duración</th><th>Resolución</th><th>Estado</th><th>Clips</th></tr>${a.map(v=>`<tr><td>${v.name}</td><td>${v.duration.toFixed(1)}s</td><td>${v.width}×${v.height}</td><td>${v.status}</td><td>${v.clips}</td></tr>`).join('')}</table>`:'<p class=muted>No hay fondos todavía.</p>'}
async function story(){let fd=new FormData();fd.append('genre',$('#genre').value);fd.append('duration',$('#storyDur').value);let j=await fetch('/api/stories',{method:'POST',body:fd}).then(r=>r.json());selectedStory=j.id;$('#storyText').value=j.text;loadStories()}
async function loadStories(){let a=await fetch('/api/stories').then(r=>r.json());$('#stories').innerHTML=a.length?a.map(x=>`<p><b>${x.title}</b> · ${x.duration}s<br><span class=muted>${x.text.slice(0,130)}…</span></p>`).join(''):'<p class=muted>No hay historias.</p>';$('#storySelect').innerHTML='<option value=0>Sin historia / solo fondo</option>'+a.map(x=>`<option value=${x.id}>${x.title}</option>`).join('')}
async function makeShort(){let fd=new FormData();fd.append('story_id',$('#storySelect').value);fd.append('duration',$('#shortDur').value);msg('#makeMsg','Optimizando la secuencia y renderizando 1080×1920…','loading');try{let r=await fetch('/api/shorts',{method:'POST',body:fd}),j=await r.json();if(!r.ok)throw Error(j.detail);selectedShort=j.id;msg('#makeMsg',`Short #${j.id} listo. <a href="${j.download}">Descargar MP4</a>`,'ok')}catch(e){msg('#makeMsg',e.message,'err')}}
async function loadShorts(){let a=await fetch('/api/shorts').then(r=>r.json());$('#shorts').innerHTML=a.length?`<table class=table><tr><th>ID</th><th>Fecha</th><th>Duración</th><th>Estado</th><th>Clips</th><th></th></tr>${a.map(x=>`<tr><td>#${x.id}</td><td>${new Date(x.created_at).toLocaleString()}</td><td>${x.duration}s</td><td>${x.status}</td><td>${x.sequence.join(', ')}</td><td><button onclick="editShort(${x.id})">Editar</button> ${x.status==='ready'?`<a href=/api/shorts/${x.id}/file>MP4</a>`:''}</td></tr>`).join('')}</table>`:'<p class=muted>No hay generaciones.</p>'}
function editShort(id){selectedShort=id;show('editor');$('#editorContent').innerHTML=`<h3>Short #${id}</h3><p>Historia, voz y subtítulos se conservan. El motor volverá a optimizar solo los clips de fondo.</p><button class=primary onclick="regen(${id})">REGENERAR FONDO</button><div id=regenMsg></div>`}
async function regen(id){msg('#regenMsg','Regenerando únicamente el fondo…','loading');try{let r=await fetch(`/api/shorts/${id}/regenerate-background`,{method:'POST'}),j=await r.json();if(!r.ok)throw Error(j.detail);msg('#regenMsg',`Listo. <a href="${j.download}">Ver MP4 nuevo</a>`,'ok')}catch(e){msg('#regenMsg',e.message,'err')}}
function msg(sel,t,c){$(sel).innerHTML=`<p class=${c}>${t}</p>`}
